=begin
#Circuit ID REST API

## Introduction Circuit ID&reg; is an innovative cloud communications platform that redefines your connectivity experience. Our cutting-edge AI-powered solution seamlessly integrates calling, meetings, messaging, voicemail, fax, SIP Trunking, mobile broadband, and mobile phone services, accessible wherever you and your devices go.                  Whether you are a beginner getting started with our API or an experienced developer looking for advanced features, this documentation site will serve as your comprehensive guide.   We are excited to have you on board and are confident that this documentation site will empower you to leverage the full potential of our REST API.  If you have any questions or require further assistance, please don't hesitate to reach out to our support team.                  Happy coding!

The version of the OpenAPI document: 0.47.22
Contact: support@circuitid.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module CircuitID
  class GetPhoneOutboundRuleAction200Response
    attr_accessor :name

    # ObjectId (unique 12 bytes ID)
    attr_accessor :group

    # ObjectId (unique 12 bytes ID)
    attr_accessor :phoneoutboundrule

    attr_accessor :status

    attr_accessor :priority

    attr_accessor :starting_chars

    attr_accessor :contains

    attr_accessor :length_type

    attr_accessor :length

    attr_accessor :append_chars

    attr_accessor :prepend_chars

    attr_accessor :range_start

    attr_accessor :range_end

    attr_accessor :remove_starting_chars

    attr_accessor :remove_ending_chars

    attr_accessor :route

    attr_accessor :routing_type

    # ObjectId (unique 12 bytes ID)
    attr_accessor :_id

    # ObjectId (unique 12 bytes ID)
    attr_accessor :created_by_user_id

    # ObjectId (unique 12 bytes ID)
    attr_accessor :updated_by_user_id

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'group' => :'group',
        :'phoneoutboundrule' => :'phoneoutboundrule',
        :'status' => :'status',
        :'priority' => :'priority',
        :'starting_chars' => :'startingChars',
        :'contains' => :'contains',
        :'length_type' => :'lengthType',
        :'length' => :'length',
        :'append_chars' => :'appendChars',
        :'prepend_chars' => :'prependChars',
        :'range_start' => :'rangeStart',
        :'range_end' => :'rangeEnd',
        :'remove_starting_chars' => :'removeStartingChars',
        :'remove_ending_chars' => :'removeEndingChars',
        :'route' => :'route',
        :'routing_type' => :'routingType',
        :'_id' => :'_id',
        :'created_by_user_id' => :'createdByUserId',
        :'updated_by_user_id' => :'updatedByUserId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'group' => :'String',
        :'phoneoutboundrule' => :'String',
        :'status' => :'Integer',
        :'priority' => :'Integer',
        :'starting_chars' => :'String',
        :'contains' => :'String',
        :'length_type' => :'String',
        :'length' => :'Integer',
        :'append_chars' => :'String',
        :'prepend_chars' => :'String',
        :'range_start' => :'Integer',
        :'range_end' => :'Integer',
        :'remove_starting_chars' => :'Integer',
        :'remove_ending_chars' => :'Integer',
        :'route' => :'String',
        :'routing_type' => :'String',
        :'_id' => :'String',
        :'created_by_user_id' => :'String',
        :'updated_by_user_id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'length_type',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'Id',
      :'Phoneoutboundruleactions',
      :'ResponseDate',
      :'ResponseUsers'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CircuitID::GetPhoneOutboundRuleAction200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CircuitID::GetPhoneOutboundRuleAction200Response`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'group')
        self.group = attributes[:'group']
      end

      if attributes.key?(:'phoneoutboundrule')
        self.phoneoutboundrule = attributes[:'phoneoutboundrule']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = STATUS::N1
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      else
        self.priority = 1
      end

      if attributes.key?(:'starting_chars')
        self.starting_chars = attributes[:'starting_chars']
      end

      if attributes.key?(:'contains')
        self.contains = attributes[:'contains']
      end

      if attributes.key?(:'length_type')
        self.length_type = attributes[:'length_type']
      end

      if attributes.key?(:'length')
        self.length = attributes[:'length']
      end

      if attributes.key?(:'append_chars')
        self.append_chars = attributes[:'append_chars']
      end

      if attributes.key?(:'prepend_chars')
        self.prepend_chars = attributes[:'prepend_chars']
      end

      if attributes.key?(:'range_start')
        self.range_start = attributes[:'range_start']
      end

      if attributes.key?(:'range_end')
        self.range_end = attributes[:'range_end']
      end

      if attributes.key?(:'remove_starting_chars')
        self.remove_starting_chars = attributes[:'remove_starting_chars']
      end

      if attributes.key?(:'remove_ending_chars')
        self.remove_ending_chars = attributes[:'remove_ending_chars']
      end

      if attributes.key?(:'route')
        self.route = attributes[:'route']
      else
        self.route = 'default'
      end

      if attributes.key?(:'routing_type')
        self.routing_type = attributes[:'routing_type']
      end

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      end

      if attributes.key?(:'created_by_user_id')
        self.created_by_user_id = attributes[:'created_by_user_id']
      end

      if attributes.key?(:'updated_by_user_id')
        self.updated_by_user_id = attributes[:'updated_by_user_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 45
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 45.')
      end

      if @phoneoutboundrule.nil?
        invalid_properties.push('invalid value for "phoneoutboundrule", phoneoutboundrule cannot be nil.')
      end

      if @priority.nil?
        invalid_properties.push('invalid value for "priority", priority cannot be nil.')
      end

      if !@starting_chars.nil? && @starting_chars.to_s.length > 20
        invalid_properties.push('invalid value for "starting_chars", the character length must be smaller than or equal to 20.')
      end

      if !@contains.nil? && @contains.to_s.length > 20
        invalid_properties.push('invalid value for "contains", the character length must be smaller than or equal to 20.')
      end

      if !@append_chars.nil? && @append_chars.to_s.length > 20
        invalid_properties.push('invalid value for "append_chars", the character length must be smaller than or equal to 20.')
      end

      if !@prepend_chars.nil? && @prepend_chars.to_s.length > 20
        invalid_properties.push('invalid value for "prepend_chars", the character length must be smaller than or equal to 20.')
      end

      if @route.nil?
        invalid_properties.push('invalid value for "route", route cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @name.to_s.length > 45
      return false if @phoneoutboundrule.nil?
      status_validator = EnumAttributeValidator.new('Integer', [1, 0])
      return false unless status_validator.valid?(@status)
      return false if @priority.nil?
      return false if !@starting_chars.nil? && @starting_chars.to_s.length > 20
      return false if !@contains.nil? && @contains.to_s.length > 20
      length_type_validator = EnumAttributeValidator.new('String', ["atleast", "exactly", "range", "any"])
      return false unless length_type_validator.valid?(@length_type)
      return false if !@append_chars.nil? && @append_chars.to_s.length > 20
      return false if !@prepend_chars.nil? && @prepend_chars.to_s.length > 20
      return false if @route.nil?
      route_validator = EnumAttributeValidator.new('String', ["default", "group", "pstn"])
      return false unless route_validator.valid?(@route)
      routing_type_validator = EnumAttributeValidator.new('String', ["priority", "lb", "simultaneous"])
      return false unless routing_type_validator.valid?(@routing_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 45
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 45.'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Integer', [1, 0])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] starting_chars Value to be assigned
    def starting_chars=(starting_chars)
      if !starting_chars.nil? && starting_chars.to_s.length > 20
        fail ArgumentError, 'invalid value for "starting_chars", the character length must be smaller than or equal to 20.'
      end

      @starting_chars = starting_chars
    end

    # Custom attribute writer method with validation
    # @param [Object] contains Value to be assigned
    def contains=(contains)
      if !contains.nil? && contains.to_s.length > 20
        fail ArgumentError, 'invalid value for "contains", the character length must be smaller than or equal to 20.'
      end

      @contains = contains
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] length_type Object to be assigned
    def length_type=(length_type)
      validator = EnumAttributeValidator.new('String', ["atleast", "exactly", "range", "any"])
      unless validator.valid?(length_type)
        fail ArgumentError, "invalid value for \"length_type\", must be one of #{validator.allowable_values}."
      end
      @length_type = length_type
    end

    # Custom attribute writer method with validation
    # @param [Object] append_chars Value to be assigned
    def append_chars=(append_chars)
      if !append_chars.nil? && append_chars.to_s.length > 20
        fail ArgumentError, 'invalid value for "append_chars", the character length must be smaller than or equal to 20.'
      end

      @append_chars = append_chars
    end

    # Custom attribute writer method with validation
    # @param [Object] prepend_chars Value to be assigned
    def prepend_chars=(prepend_chars)
      if !prepend_chars.nil? && prepend_chars.to_s.length > 20
        fail ArgumentError, 'invalid value for "prepend_chars", the character length must be smaller than or equal to 20.'
      end

      @prepend_chars = prepend_chars
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] route Object to be assigned
    def route=(route)
      validator = EnumAttributeValidator.new('String', ["default", "group", "pstn"])
      unless validator.valid?(route)
        fail ArgumentError, "invalid value for \"route\", must be one of #{validator.allowable_values}."
      end
      @route = route
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] routing_type Object to be assigned
    def routing_type=(routing_type)
      validator = EnumAttributeValidator.new('String', ["priority", "lb", "simultaneous"])
      unless validator.valid?(routing_type)
        fail ArgumentError, "invalid value for \"routing_type\", must be one of #{validator.allowable_values}."
      end
      @routing_type = routing_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          group == o.group &&
          phoneoutboundrule == o.phoneoutboundrule &&
          status == o.status &&
          priority == o.priority &&
          starting_chars == o.starting_chars &&
          contains == o.contains &&
          length_type == o.length_type &&
          length == o.length &&
          append_chars == o.append_chars &&
          prepend_chars == o.prepend_chars &&
          range_start == o.range_start &&
          range_end == o.range_end &&
          remove_starting_chars == o.remove_starting_chars &&
          remove_ending_chars == o.remove_ending_chars &&
          route == o.route &&
          routing_type == o.routing_type &&
          _id == o._id &&
          created_by_user_id == o.created_by_user_id &&
          updated_by_user_id == o.updated_by_user_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, group, phoneoutboundrule, status, priority, starting_chars, contains, length_type, length, append_chars, prepend_chars, range_start, range_end, remove_starting_chars, remove_ending_chars, route, routing_type, _id, created_by_user_id, updated_by_user_id, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CircuitID.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
