=begin
#Circuit ID REST API

## Introduction Circuit ID&reg; is an innovative cloud communications platform that redefines your connectivity experience. Our cutting-edge AI-powered solution seamlessly integrates calling, meetings, messaging, voicemail, fax, SIP Trunking, mobile broadband, and mobile phone services, accessible wherever you and your devices go.                  Whether you are a beginner getting started with our API or an experienced developer looking for advanced features, this documentation site will serve as your comprehensive guide.   We are excited to have you on board and are confident that this documentation site will empower you to leverage the full potential of our REST API.  If you have any questions or require further assistance, please don't hesitate to reach out to our support team.                  Happy coding!

The version of the OpenAPI document: 0.47.22
Contact: support@circuitid.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module CircuitID
  class MessagebrandsCreateOrPatch
    attr_accessor :name

    attr_accessor :brand_id

    attr_accessor :ein

    # ObjectId (unique 12 bytes ID)
    attr_accessor :user

    # ObjectId (unique 12 bytes ID)
    attr_accessor :order

    attr_accessor :brand_relationship

    attr_accessor :vertical

    attr_accessor :entity_type

    attr_accessor :csp_id

    attr_accessor :ein_issuing_country

    attr_accessor :universal_ein

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'brand_id' => :'brandId',
        :'ein' => :'ein',
        :'user' => :'user',
        :'order' => :'order',
        :'brand_relationship' => :'brandRelationship',
        :'vertical' => :'vertical',
        :'entity_type' => :'entityType',
        :'csp_id' => :'cspId',
        :'ein_issuing_country' => :'einIssuingCountry',
        :'universal_ein' => :'universalEin'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'brand_id' => :'String',
        :'ein' => :'String',
        :'user' => :'String',
        :'order' => :'String',
        :'brand_relationship' => :'String',
        :'vertical' => :'String',
        :'entity_type' => :'String',
        :'csp_id' => :'String',
        :'ein_issuing_country' => :'String',
        :'universal_ein' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CircuitID::MessagebrandsCreateOrPatch` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CircuitID::MessagebrandsCreateOrPatch`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'brand_id')
        self.brand_id = attributes[:'brand_id']
      end

      if attributes.key?(:'ein')
        self.ein = attributes[:'ein']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'order')
        self.order = attributes[:'order']
      end

      if attributes.key?(:'brand_relationship')
        self.brand_relationship = attributes[:'brand_relationship']
      end

      if attributes.key?(:'vertical')
        self.vertical = attributes[:'vertical']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'csp_id')
        self.csp_id = attributes[:'csp_id']
      end

      if attributes.key?(:'ein_issuing_country')
        self.ein_issuing_country = attributes[:'ein_issuing_country']
      end

      if attributes.key?(:'universal_ein')
        self.universal_ein = attributes[:'universal_ein']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 45
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 45.')
      end

      if !@brand_id.nil? && @brand_id.to_s.length > 45
        invalid_properties.push('invalid value for "brand_id", the character length must be smaller than or equal to 45.')
      end

      if @ein.nil?
        invalid_properties.push('invalid value for "ein", ein cannot be nil.')
      end

      if @ein.to_s.length > 20
        invalid_properties.push('invalid value for "ein", the character length must be smaller than or equal to 20.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @order.nil?
        invalid_properties.push('invalid value for "order", order cannot be nil.')
      end

      if !@brand_relationship.nil? && @brand_relationship.to_s.length > 45
        invalid_properties.push('invalid value for "brand_relationship", the character length must be smaller than or equal to 45.')
      end

      if !@vertical.nil? && @vertical.to_s.length > 45
        invalid_properties.push('invalid value for "vertical", the character length must be smaller than or equal to 45.')
      end

      if !@entity_type.nil? && @entity_type.to_s.length > 45
        invalid_properties.push('invalid value for "entity_type", the character length must be smaller than or equal to 45.')
      end

      if !@csp_id.nil? && @csp_id.to_s.length > 45
        invalid_properties.push('invalid value for "csp_id", the character length must be smaller than or equal to 45.')
      end

      if !@ein_issuing_country.nil? && @ein_issuing_country.to_s.length > 2
        invalid_properties.push('invalid value for "ein_issuing_country", the character length must be smaller than or equal to 2.')
      end

      if !@universal_ein.nil? && @universal_ein.to_s.length > 45
        invalid_properties.push('invalid value for "universal_ein", the character length must be smaller than or equal to 45.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @name.to_s.length > 45
      return false if !@brand_id.nil? && @brand_id.to_s.length > 45
      return false if @ein.nil?
      return false if @ein.to_s.length > 20
      return false if @user.nil?
      return false if @order.nil?
      return false if !@brand_relationship.nil? && @brand_relationship.to_s.length > 45
      return false if !@vertical.nil? && @vertical.to_s.length > 45
      return false if !@entity_type.nil? && @entity_type.to_s.length > 45
      return false if !@csp_id.nil? && @csp_id.to_s.length > 45
      return false if !@ein_issuing_country.nil? && @ein_issuing_country.to_s.length > 2
      return false if !@universal_ein.nil? && @universal_ein.to_s.length > 45
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 45
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 45.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] brand_id Value to be assigned
    def brand_id=(brand_id)
      if !brand_id.nil? && brand_id.to_s.length > 45
        fail ArgumentError, 'invalid value for "brand_id", the character length must be smaller than or equal to 45.'
      end

      @brand_id = brand_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ein Value to be assigned
    def ein=(ein)
      if ein.nil?
        fail ArgumentError, 'ein cannot be nil'
      end

      if ein.to_s.length > 20
        fail ArgumentError, 'invalid value for "ein", the character length must be smaller than or equal to 20.'
      end

      @ein = ein
    end

    # Custom attribute writer method with validation
    # @param [Object] brand_relationship Value to be assigned
    def brand_relationship=(brand_relationship)
      if !brand_relationship.nil? && brand_relationship.to_s.length > 45
        fail ArgumentError, 'invalid value for "brand_relationship", the character length must be smaller than or equal to 45.'
      end

      @brand_relationship = brand_relationship
    end

    # Custom attribute writer method with validation
    # @param [Object] vertical Value to be assigned
    def vertical=(vertical)
      if !vertical.nil? && vertical.to_s.length > 45
        fail ArgumentError, 'invalid value for "vertical", the character length must be smaller than or equal to 45.'
      end

      @vertical = vertical
    end

    # Custom attribute writer method with validation
    # @param [Object] entity_type Value to be assigned
    def entity_type=(entity_type)
      if !entity_type.nil? && entity_type.to_s.length > 45
        fail ArgumentError, 'invalid value for "entity_type", the character length must be smaller than or equal to 45.'
      end

      @entity_type = entity_type
    end

    # Custom attribute writer method with validation
    # @param [Object] csp_id Value to be assigned
    def csp_id=(csp_id)
      if !csp_id.nil? && csp_id.to_s.length > 45
        fail ArgumentError, 'invalid value for "csp_id", the character length must be smaller than or equal to 45.'
      end

      @csp_id = csp_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ein_issuing_country Value to be assigned
    def ein_issuing_country=(ein_issuing_country)
      if !ein_issuing_country.nil? && ein_issuing_country.to_s.length > 2
        fail ArgumentError, 'invalid value for "ein_issuing_country", the character length must be smaller than or equal to 2.'
      end

      @ein_issuing_country = ein_issuing_country
    end

    # Custom attribute writer method with validation
    # @param [Object] universal_ein Value to be assigned
    def universal_ein=(universal_ein)
      if !universal_ein.nil? && universal_ein.to_s.length > 45
        fail ArgumentError, 'invalid value for "universal_ein", the character length must be smaller than or equal to 45.'
      end

      @universal_ein = universal_ein
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          brand_id == o.brand_id &&
          ein == o.ein &&
          user == o.user &&
          order == o.order &&
          brand_relationship == o.brand_relationship &&
          vertical == o.vertical &&
          entity_type == o.entity_type &&
          csp_id == o.csp_id &&
          ein_issuing_country == o.ein_issuing_country &&
          universal_ein == o.universal_ein
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, brand_id, ein, user, order, brand_relationship, vertical, entity_type, csp_id, ein_issuing_country, universal_ein].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CircuitID.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
