=begin
#Circuit ID REST API

## Introduction Circuit ID&reg; is an innovative cloud communications platform that redefines your connectivity experience. Our cutting-edge AI-powered solution seamlessly integrates calling, meetings, messaging, voicemail, fax, SIP Trunking, mobile broadband, and mobile phone services, accessible wherever you and your devices go.                  Whether you are a beginner getting started with our API or an experienced developer looking for advanced features, this documentation site will serve as your comprehensive guide.   We are excited to have you on board and are confident that this documentation site will empower you to leverage the full potential of our REST API.  If you have any questions or require further assistance, please don't hesitate to reach out to our support team.                  Happy coding!

The version of the OpenAPI document: 0.47.20
Contact: support@circuitid.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module CircuitID
  class Numberports
    attr_accessor :numbers

    attr_accessor :name

    attr_accessor :type

    attr_accessor :type_of_service

    attr_accessor :authorized_person

    attr_accessor :desired_due_date

    attr_accessor :account_number

    attr_accessor :account_phone_number

    # ObjectId (unique 12 bytes ID)
    attr_accessor :office

    attr_accessor :e911

    # ObjectId (unique 12 bytes ID)
    attr_accessor :invoice

    attr_accessor :status

    attr_accessor :destination_type

    # ObjectId (unique 12 bytes ID)
    attr_accessor :destination

    attr_accessor :ref

    attr_accessor :call_forwarding_destination

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'numbers' => :'numbers',
        :'name' => :'name',
        :'type' => :'type',
        :'type_of_service' => :'typeOfService',
        :'authorized_person' => :'authorizedPerson',
        :'desired_due_date' => :'desiredDueDate',
        :'account_number' => :'accountNumber',
        :'account_phone_number' => :'accountPhoneNumber',
        :'office' => :'office',
        :'e911' => :'e911',
        :'invoice' => :'invoice',
        :'status' => :'status',
        :'destination_type' => :'destinationType',
        :'destination' => :'destination',
        :'ref' => :'ref',
        :'call_forwarding_destination' => :'callForwardingDestination'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'numbers' => :'Array<String>',
        :'name' => :'String',
        :'type' => :'String',
        :'type_of_service' => :'String',
        :'authorized_person' => :'String',
        :'desired_due_date' => :'Time',
        :'account_number' => :'String',
        :'account_phone_number' => :'String',
        :'office' => :'String',
        :'e911' => :'Integer',
        :'invoice' => :'String',
        :'status' => :'String',
        :'destination_type' => :'String',
        :'destination' => :'String',
        :'ref' => :'String',
        :'call_forwarding_destination' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CircuitID::Numberports` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CircuitID::Numberports`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'numbers')
        if (value = attributes[:'numbers']).is_a?(Array)
          self.numbers = value
        end
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'port in'
      end

      if attributes.key?(:'type_of_service')
        self.type_of_service = attributes[:'type_of_service']
      end

      if attributes.key?(:'authorized_person')
        self.authorized_person = attributes[:'authorized_person']
      end

      if attributes.key?(:'desired_due_date')
        self.desired_due_date = attributes[:'desired_due_date']
      end

      if attributes.key?(:'account_number')
        self.account_number = attributes[:'account_number']
      end

      if attributes.key?(:'account_phone_number')
        self.account_phone_number = attributes[:'account_phone_number']
      end

      if attributes.key?(:'office')
        self.office = attributes[:'office']
      end

      if attributes.key?(:'e911')
        self.e911 = attributes[:'e911']
      else
        self.e911 = E911::N0
      end

      if attributes.key?(:'invoice')
        self.invoice = attributes[:'invoice']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = 'processing'
      end

      if attributes.key?(:'destination_type')
        self.destination_type = attributes[:'destination_type']
      end

      if attributes.key?(:'destination')
        self.destination = attributes[:'destination']
      end

      if attributes.key?(:'ref')
        self.ref = attributes[:'ref']
      end

      if attributes.key?(:'call_forwarding_destination')
        self.call_forwarding_destination = attributes[:'call_forwarding_destination']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @numbers.nil?
        invalid_properties.push('invalid value for "numbers", numbers cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 45
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 45.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @type_of_service.nil?
        invalid_properties.push('invalid value for "type_of_service", type_of_service cannot be nil.')
      end

      if @authorized_person.nil?
        invalid_properties.push('invalid value for "authorized_person", authorized_person cannot be nil.')
      end

      if @authorized_person.to_s.length > 45
        invalid_properties.push('invalid value for "authorized_person", the character length must be smaller than or equal to 45.')
      end

      if @desired_due_date.nil?
        invalid_properties.push('invalid value for "desired_due_date", desired_due_date cannot be nil.')
      end

      if @account_number.nil?
        invalid_properties.push('invalid value for "account_number", account_number cannot be nil.')
      end

      if @account_number.to_s.length > 45
        invalid_properties.push('invalid value for "account_number", the character length must be smaller than or equal to 45.')
      end

      if @account_phone_number.nil?
        invalid_properties.push('invalid value for "account_phone_number", account_phone_number cannot be nil.')
      end

      if @account_phone_number.to_s.length > 20
        invalid_properties.push('invalid value for "account_phone_number", the character length must be smaller than or equal to 20.')
      end

      if @account_phone_number.to_s.length < 10
        invalid_properties.push('invalid value for "account_phone_number", the character length must be great than or equal to 10.')
      end

      if @office.nil?
        invalid_properties.push('invalid value for "office", office cannot be nil.')
      end

      if @invoice.nil?
        invalid_properties.push('invalid value for "invoice", invoice cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @destination_type.nil?
        invalid_properties.push('invalid value for "destination_type", destination_type cannot be nil.')
      end

      if !@ref.nil? && @ref.to_s.length > 100
        invalid_properties.push('invalid value for "ref", the character length must be smaller than or equal to 100.')
      end

      if !@ref.nil? && @ref.to_s.length < 5
        invalid_properties.push('invalid value for "ref", the character length must be great than or equal to 5.')
      end

      if !@call_forwarding_destination.nil? && @call_forwarding_destination.to_s.length > 45
        invalid_properties.push('invalid value for "call_forwarding_destination", the character length must be smaller than or equal to 45.')
      end

      if !@call_forwarding_destination.nil? && @call_forwarding_destination.to_s.length < 10
        invalid_properties.push('invalid value for "call_forwarding_destination", the character length must be great than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @numbers.nil?
      return false if @name.nil?
      return false if @name.to_s.length > 45
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["port in", "port out"])
      return false unless type_validator.valid?(@type)
      return false if @type_of_service.nil?
      type_of_service_validator = EnumAttributeValidator.new('String', ["business", "residence"])
      return false unless type_of_service_validator.valid?(@type_of_service)
      return false if @authorized_person.nil?
      return false if @authorized_person.to_s.length > 45
      return false if @desired_due_date.nil?
      return false if @account_number.nil?
      return false if @account_number.to_s.length > 45
      return false if @account_phone_number.nil?
      return false if @account_phone_number.to_s.length > 20
      return false if @account_phone_number.to_s.length < 10
      return false if @office.nil?
      e911_validator = EnumAttributeValidator.new('Integer', [1, 0])
      return false unless e911_validator.valid?(@e911)
      return false if @invoice.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["processing", "failed", "error", "completed"])
      return false unless status_validator.valid?(@status)
      return false if @destination_type.nil?
      destination_type_validator = EnumAttributeValidator.new('String', ["announcements", "directories", "park", "numbers", "menus", "users", "servers", "inboundrules", "callqueues", "faxaccounts", "callforwarding", "hangup", "phoneinboundrules", "voicemailaccounts"])
      return false unless destination_type_validator.valid?(@destination_type)
      return false if !@ref.nil? && @ref.to_s.length > 100
      return false if !@ref.nil? && @ref.to_s.length < 5
      return false if !@call_forwarding_destination.nil? && @call_forwarding_destination.to_s.length > 45
      return false if !@call_forwarding_destination.nil? && @call_forwarding_destination.to_s.length < 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 45
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 45.'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["port in", "port out"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type_of_service Object to be assigned
    def type_of_service=(type_of_service)
      validator = EnumAttributeValidator.new('String', ["business", "residence"])
      unless validator.valid?(type_of_service)
        fail ArgumentError, "invalid value for \"type_of_service\", must be one of #{validator.allowable_values}."
      end
      @type_of_service = type_of_service
    end

    # Custom attribute writer method with validation
    # @param [Object] authorized_person Value to be assigned
    def authorized_person=(authorized_person)
      if authorized_person.nil?
        fail ArgumentError, 'authorized_person cannot be nil'
      end

      if authorized_person.to_s.length > 45
        fail ArgumentError, 'invalid value for "authorized_person", the character length must be smaller than or equal to 45.'
      end

      @authorized_person = authorized_person
    end

    # Custom attribute writer method with validation
    # @param [Object] account_number Value to be assigned
    def account_number=(account_number)
      if account_number.nil?
        fail ArgumentError, 'account_number cannot be nil'
      end

      if account_number.to_s.length > 45
        fail ArgumentError, 'invalid value for "account_number", the character length must be smaller than or equal to 45.'
      end

      @account_number = account_number
    end

    # Custom attribute writer method with validation
    # @param [Object] account_phone_number Value to be assigned
    def account_phone_number=(account_phone_number)
      if account_phone_number.nil?
        fail ArgumentError, 'account_phone_number cannot be nil'
      end

      if account_phone_number.to_s.length > 20
        fail ArgumentError, 'invalid value for "account_phone_number", the character length must be smaller than or equal to 20.'
      end

      if account_phone_number.to_s.length < 10
        fail ArgumentError, 'invalid value for "account_phone_number", the character length must be great than or equal to 10.'
      end

      @account_phone_number = account_phone_number
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] e911 Object to be assigned
    def e911=(e911)
      validator = EnumAttributeValidator.new('Integer', [1, 0])
      unless validator.valid?(e911)
        fail ArgumentError, "invalid value for \"e911\", must be one of #{validator.allowable_values}."
      end
      @e911 = e911
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["processing", "failed", "error", "completed"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] destination_type Object to be assigned
    def destination_type=(destination_type)
      validator = EnumAttributeValidator.new('String', ["announcements", "directories", "park", "numbers", "menus", "users", "servers", "inboundrules", "callqueues", "faxaccounts", "callforwarding", "hangup", "phoneinboundrules", "voicemailaccounts"])
      unless validator.valid?(destination_type)
        fail ArgumentError, "invalid value for \"destination_type\", must be one of #{validator.allowable_values}."
      end
      @destination_type = destination_type
    end

    # Custom attribute writer method with validation
    # @param [Object] ref Value to be assigned
    def ref=(ref)
      if !ref.nil? && ref.to_s.length > 100
        fail ArgumentError, 'invalid value for "ref", the character length must be smaller than or equal to 100.'
      end

      if !ref.nil? && ref.to_s.length < 5
        fail ArgumentError, 'invalid value for "ref", the character length must be great than or equal to 5.'
      end

      @ref = ref
    end

    # Custom attribute writer method with validation
    # @param [Object] call_forwarding_destination Value to be assigned
    def call_forwarding_destination=(call_forwarding_destination)
      if !call_forwarding_destination.nil? && call_forwarding_destination.to_s.length > 45
        fail ArgumentError, 'invalid value for "call_forwarding_destination", the character length must be smaller than or equal to 45.'
      end

      if !call_forwarding_destination.nil? && call_forwarding_destination.to_s.length < 10
        fail ArgumentError, 'invalid value for "call_forwarding_destination", the character length must be great than or equal to 10.'
      end

      @call_forwarding_destination = call_forwarding_destination
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          numbers == o.numbers &&
          name == o.name &&
          type == o.type &&
          type_of_service == o.type_of_service &&
          authorized_person == o.authorized_person &&
          desired_due_date == o.desired_due_date &&
          account_number == o.account_number &&
          account_phone_number == o.account_phone_number &&
          office == o.office &&
          e911 == o.e911 &&
          invoice == o.invoice &&
          status == o.status &&
          destination_type == o.destination_type &&
          destination == o.destination &&
          ref == o.ref &&
          call_forwarding_destination == o.call_forwarding_destination
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [numbers, name, type, type_of_service, authorized_person, desired_due_date, account_number, account_phone_number, office, e911, invoice, status, destination_type, destination, ref, call_forwarding_destination].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CircuitID.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
