=begin
#Circuit ID REST API

## Introduction Circuit ID&reg; is an innovative cloud communications platform that redefines your connectivity experience. Our cutting-edge AI-powered solution seamlessly integrates calling, meetings, messaging, voicemail, fax, SIP Trunking, mobile broadband, and mobile phone services, accessible wherever you and your devices go.                  Whether you are a beginner getting started with our API or an experienced developer looking for advanced features, this documentation site will serve as your comprehensive guide.   We are excited to have you on board and are confident that this documentation site will empower you to leverage the full potential of our REST API.  If you have any questions or require further assistance, please don't hesitate to reach out to our support team.                  Happy coding!

The version of the OpenAPI document: 0.47.8
Contact: support@circuitid.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module CircuitIDAPIClient
  class Users
    attr_accessor :email

    attr_accessor :password

    attr_accessor :sip_password

    attr_accessor :turn_password

    attr_accessor :first

    attr_accessor :last

    attr_accessor :mobile_phone

    attr_accessor :business_phone

    attr_accessor :extension

    attr_accessor :custom_caller_id

    attr_accessor :job_title

    attr_accessor :department

    # ObjectId (unique 12 bytes ID)
    attr_accessor :office

    attr_accessor :avatar

    attr_accessor :language

    attr_accessor :is_primary

    attr_accessor :status

    attr_accessor :vm_greeting_type

    attr_accessor :vm_timeout

    # ObjectId (unique 12 bytes ID)
    attr_accessor :vm_file

    attr_accessor :vm_playback_number

    attr_accessor :pin

    # ObjectId (unique 12 bytes ID)
    attr_accessor :number

    # ObjectId (unique 12 bytes ID)
    attr_accessor :region

    attr_accessor :caller_id_number

    attr_accessor :admin_permission

    attr_accessor :billing_permission

    attr_accessor :phone_permission

    attr_accessor :agile_permission

    attr_accessor :job_server_permission

    attr_accessor :media_server_permission

    attr_accessor :mail_server_permission

    attr_accessor :super_admin_permission

    attr_accessor :timezone

    attr_accessor :vm_transcription

    attr_accessor :communication

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email' => :'email',
        :'password' => :'password',
        :'sip_password' => :'sipPassword',
        :'turn_password' => :'turnPassword',
        :'first' => :'first',
        :'last' => :'last',
        :'mobile_phone' => :'mobilePhone',
        :'business_phone' => :'businessPhone',
        :'extension' => :'extension',
        :'custom_caller_id' => :'customCallerId',
        :'job_title' => :'jobTitle',
        :'department' => :'department',
        :'office' => :'office',
        :'avatar' => :'avatar',
        :'language' => :'language',
        :'is_primary' => :'isPrimary',
        :'status' => :'status',
        :'vm_greeting_type' => :'vmGreetingType',
        :'vm_timeout' => :'vmTimeout',
        :'vm_file' => :'vmFile',
        :'vm_playback_number' => :'vmPlaybackNumber',
        :'pin' => :'pin',
        :'number' => :'number',
        :'region' => :'region',
        :'caller_id_number' => :'callerIdNumber',
        :'admin_permission' => :'adminPermission',
        :'billing_permission' => :'billingPermission',
        :'phone_permission' => :'phonePermission',
        :'agile_permission' => :'agilePermission',
        :'job_server_permission' => :'jobServerPermission',
        :'media_server_permission' => :'mediaServerPermission',
        :'mail_server_permission' => :'mailServerPermission',
        :'super_admin_permission' => :'superAdminPermission',
        :'timezone' => :'timezone',
        :'vm_transcription' => :'vmTranscription',
        :'communication' => :'communication'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email' => :'Object',
        :'password' => :'Object',
        :'sip_password' => :'Object',
        :'turn_password' => :'Object',
        :'first' => :'Object',
        :'last' => :'Object',
        :'mobile_phone' => :'Object',
        :'business_phone' => :'Object',
        :'extension' => :'Object',
        :'custom_caller_id' => :'Object',
        :'job_title' => :'Object',
        :'department' => :'Object',
        :'office' => :'Object',
        :'avatar' => :'Object',
        :'language' => :'Object',
        :'is_primary' => :'Object',
        :'status' => :'Object',
        :'vm_greeting_type' => :'Object',
        :'vm_timeout' => :'Object',
        :'vm_file' => :'Object',
        :'vm_playback_number' => :'Object',
        :'pin' => :'Object',
        :'number' => :'Object',
        :'region' => :'Object',
        :'caller_id_number' => :'Object',
        :'admin_permission' => :'Object',
        :'billing_permission' => :'Object',
        :'phone_permission' => :'Object',
        :'agile_permission' => :'Object',
        :'job_server_permission' => :'Object',
        :'media_server_permission' => :'Object',
        :'mail_server_permission' => :'Object',
        :'super_admin_permission' => :'Object',
        :'timezone' => :'Object',
        :'vm_transcription' => :'Object',
        :'communication' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'email',
        :'password',
        :'sip_password',
        :'turn_password',
        :'first',
        :'last',
        :'mobile_phone',
        :'business_phone',
        :'extension',
        :'custom_caller_id',
        :'job_title',
        :'department',
        :'office',
        :'avatar',
        :'language',
        :'is_primary',
        :'status',
        :'vm_greeting_type',
        :'vm_timeout',
        :'vm_file',
        :'vm_playback_number',
        :'pin',
        :'number',
        :'region',
        :'caller_id_number',
        :'admin_permission',
        :'billing_permission',
        :'phone_permission',
        :'agile_permission',
        :'job_server_permission',
        :'media_server_permission',
        :'mail_server_permission',
        :'super_admin_permission',
        :'timezone',
        :'vm_transcription',
        :'communication'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CircuitIDAPIClient::Users` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CircuitIDAPIClient::Users`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.key?(:'sip_password')
        self.sip_password = attributes[:'sip_password']
      end

      if attributes.key?(:'turn_password')
        self.turn_password = attributes[:'turn_password']
      end

      if attributes.key?(:'first')
        self.first = attributes[:'first']
      end

      if attributes.key?(:'last')
        self.last = attributes[:'last']
      end

      if attributes.key?(:'mobile_phone')
        self.mobile_phone = attributes[:'mobile_phone']
      end

      if attributes.key?(:'business_phone')
        self.business_phone = attributes[:'business_phone']
      end

      if attributes.key?(:'extension')
        self.extension = attributes[:'extension']
      end

      if attributes.key?(:'custom_caller_id')
        self.custom_caller_id = attributes[:'custom_caller_id']
      end

      if attributes.key?(:'job_title')
        self.job_title = attributes[:'job_title']
      end

      if attributes.key?(:'department')
        self.department = attributes[:'department']
      end

      if attributes.key?(:'office')
        self.office = attributes[:'office']
      end

      if attributes.key?(:'avatar')
        self.avatar = attributes[:'avatar']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'is_primary')
        self.is_primary = attributes[:'is_primary']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'vm_greeting_type')
        self.vm_greeting_type = attributes[:'vm_greeting_type']
      end

      if attributes.key?(:'vm_timeout')
        self.vm_timeout = attributes[:'vm_timeout']
      end

      if attributes.key?(:'vm_file')
        self.vm_file = attributes[:'vm_file']
      end

      if attributes.key?(:'vm_playback_number')
        self.vm_playback_number = attributes[:'vm_playback_number']
      end

      if attributes.key?(:'pin')
        self.pin = attributes[:'pin']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'caller_id_number')
        self.caller_id_number = attributes[:'caller_id_number']
      end

      if attributes.key?(:'admin_permission')
        self.admin_permission = attributes[:'admin_permission']
      end

      if attributes.key?(:'billing_permission')
        self.billing_permission = attributes[:'billing_permission']
      end

      if attributes.key?(:'phone_permission')
        self.phone_permission = attributes[:'phone_permission']
      end

      if attributes.key?(:'agile_permission')
        self.agile_permission = attributes[:'agile_permission']
      end

      if attributes.key?(:'job_server_permission')
        self.job_server_permission = attributes[:'job_server_permission']
      end

      if attributes.key?(:'media_server_permission')
        self.media_server_permission = attributes[:'media_server_permission']
      end

      if attributes.key?(:'mail_server_permission')
        self.mail_server_permission = attributes[:'mail_server_permission']
      end

      if attributes.key?(:'super_admin_permission')
        self.super_admin_permission = attributes[:'super_admin_permission']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'vm_transcription')
        self.vm_transcription = attributes[:'vm_transcription']
      end

      if attributes.key?(:'communication')
        self.communication = attributes[:'communication']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @email.to_s.length > 255
        invalid_properties.push('invalid value for "email", the character length must be smaller than or equal to 255.')
      end

      if @email.to_s.length < 5
        invalid_properties.push('invalid value for "email", the character length must be great than or equal to 5.')
      end

      if @password.to_s.length > 255
        invalid_properties.push('invalid value for "password", the character length must be smaller than or equal to 255.')
      end

      if @password.to_s.length < 8
        invalid_properties.push('invalid value for "password", the character length must be great than or equal to 8.')
      end

      if @sip_password.to_s.length > 45
        invalid_properties.push('invalid value for "sip_password", the character length must be smaller than or equal to 45.')
      end

      if @sip_password.to_s.length < 8
        invalid_properties.push('invalid value for "sip_password", the character length must be great than or equal to 8.')
      end

      if !@turn_password.nil? && @turn_password.to_s.length > 45
        invalid_properties.push('invalid value for "turn_password", the character length must be smaller than or equal to 45.')
      end

      if !@turn_password.nil? && @turn_password.to_s.length < 8
        invalid_properties.push('invalid value for "turn_password", the character length must be great than or equal to 8.')
      end

      if @first.to_s.length > 45
        invalid_properties.push('invalid value for "first", the character length must be smaller than or equal to 45.')
      end

      if @last.to_s.length > 45
        invalid_properties.push('invalid value for "last", the character length must be smaller than or equal to 45.')
      end

      if !@mobile_phone.nil? && @mobile_phone.to_s.length > 20
        invalid_properties.push('invalid value for "mobile_phone", the character length must be smaller than or equal to 20.')
      end

      if !@business_phone.nil? && @business_phone.to_s.length > 20
        invalid_properties.push('invalid value for "business_phone", the character length must be smaller than or equal to 20.')
      end

      if !@business_phone.nil? && @business_phone.to_s.length < 7
        invalid_properties.push('invalid value for "business_phone", the character length must be great than or equal to 7.')
      end

      if !@job_title.nil? && @job_title.to_s.length > 45
        invalid_properties.push('invalid value for "job_title", the character length must be smaller than or equal to 45.')
      end

      if !@department.nil? && @department.to_s.length > 45
        invalid_properties.push('invalid value for "department", the character length must be smaller than or equal to 45.')
      end

      if !@avatar.nil? && @avatar.to_s.length > 255
        invalid_properties.push('invalid value for "avatar", the character length must be smaller than or equal to 255.')
      end

      if !@language.nil? && @language.to_s.length > 5
        invalid_properties.push('invalid value for "language", the character length must be smaller than or equal to 5.')
      end

      if !@vm_playback_number.nil? && @vm_playback_number.to_s.length > 20
        invalid_properties.push('invalid value for "vm_playback_number", the character length must be smaller than or equal to 20.')
      end

      if !@caller_id_number.nil? && @caller_id_number.to_s.length > 20
        invalid_properties.push('invalid value for "caller_id_number", the character length must be smaller than or equal to 20.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @email.to_s.length > 255
      return false if @email.to_s.length < 5
      return false if @password.to_s.length > 255
      return false if @password.to_s.length < 8
      return false if @sip_password.to_s.length > 45
      return false if @sip_password.to_s.length < 8
      return false if !@turn_password.nil? && @turn_password.to_s.length > 45
      return false if !@turn_password.nil? && @turn_password.to_s.length < 8
      return false if @first.to_s.length > 45
      return false if @last.to_s.length > 45
      return false if !@mobile_phone.nil? && @mobile_phone.to_s.length > 20
      return false if !@business_phone.nil? && @business_phone.to_s.length > 20
      return false if !@business_phone.nil? && @business_phone.to_s.length < 7
      return false if !@job_title.nil? && @job_title.to_s.length > 45
      return false if !@department.nil? && @department.to_s.length > 45
      return false if !@avatar.nil? && @avatar.to_s.length > 255
      language_validator = EnumAttributeValidator.new('Object', ["fr", "en", "ja", "de", "es"])
      return false unless language_validator.valid?(@language)
      return false if !@language.nil? && @language.to_s.length > 5
      is_primary_validator = EnumAttributeValidator.new('Object', ["1", "0"])
      return false unless is_primary_validator.valid?(@is_primary)
      status_validator = EnumAttributeValidator.new('Object', ["active", "disabled", "terminated"])
      return false unless status_validator.valid?(@status)
      vm_greeting_type_validator = EnumAttributeValidator.new('Object', ["default", "mp3", "number"])
      return false unless vm_greeting_type_validator.valid?(@vm_greeting_type)
      return false if !@vm_playback_number.nil? && @vm_playback_number.to_s.length > 20
      return false if !@caller_id_number.nil? && @caller_id_number.to_s.length > 20
      admin_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless admin_permission_validator.valid?(@admin_permission)
      billing_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless billing_permission_validator.valid?(@billing_permission)
      phone_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless phone_permission_validator.valid?(@phone_permission)
      agile_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless agile_permission_validator.valid?(@agile_permission)
      job_server_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless job_server_permission_validator.valid?(@job_server_permission)
      media_server_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless media_server_permission_validator.valid?(@media_server_permission)
      mail_server_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless mail_server_permission_validator.valid?(@mail_server_permission)
      super_admin_permission_validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      return false unless super_admin_permission_validator.valid?(@super_admin_permission)
      vm_transcription_validator = EnumAttributeValidator.new('Object', ["1", "0"])
      return false unless vm_transcription_validator.valid?(@vm_transcription)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.to_s.length > 255
        fail ArgumentError, 'invalid value for "email", the character length must be smaller than or equal to 255.'
      end

      if email.to_s.length < 5
        fail ArgumentError, 'invalid value for "email", the character length must be great than or equal to 5.'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] password Value to be assigned
    def password=(password)
      if password.to_s.length > 255
        fail ArgumentError, 'invalid value for "password", the character length must be smaller than or equal to 255.'
      end

      if password.to_s.length < 8
        fail ArgumentError, 'invalid value for "password", the character length must be great than or equal to 8.'
      end

      @password = password
    end

    # Custom attribute writer method with validation
    # @param [Object] sip_password Value to be assigned
    def sip_password=(sip_password)
      if sip_password.to_s.length > 45
        fail ArgumentError, 'invalid value for "sip_password", the character length must be smaller than or equal to 45.'
      end

      if sip_password.to_s.length < 8
        fail ArgumentError, 'invalid value for "sip_password", the character length must be great than or equal to 8.'
      end

      @sip_password = sip_password
    end

    # Custom attribute writer method with validation
    # @param [Object] turn_password Value to be assigned
    def turn_password=(turn_password)
      if !turn_password.nil? && turn_password.to_s.length > 45
        fail ArgumentError, 'invalid value for "turn_password", the character length must be smaller than or equal to 45.'
      end

      if !turn_password.nil? && turn_password.to_s.length < 8
        fail ArgumentError, 'invalid value for "turn_password", the character length must be great than or equal to 8.'
      end

      @turn_password = turn_password
    end

    # Custom attribute writer method with validation
    # @param [Object] first Value to be assigned
    def first=(first)
      if first.to_s.length > 45
        fail ArgumentError, 'invalid value for "first", the character length must be smaller than or equal to 45.'
      end

      @first = first
    end

    # Custom attribute writer method with validation
    # @param [Object] last Value to be assigned
    def last=(last)
      if last.to_s.length > 45
        fail ArgumentError, 'invalid value for "last", the character length must be smaller than or equal to 45.'
      end

      @last = last
    end

    # Custom attribute writer method with validation
    # @param [Object] mobile_phone Value to be assigned
    def mobile_phone=(mobile_phone)
      if !mobile_phone.nil? && mobile_phone.to_s.length > 20
        fail ArgumentError, 'invalid value for "mobile_phone", the character length must be smaller than or equal to 20.'
      end

      @mobile_phone = mobile_phone
    end

    # Custom attribute writer method with validation
    # @param [Object] business_phone Value to be assigned
    def business_phone=(business_phone)
      if !business_phone.nil? && business_phone.to_s.length > 20
        fail ArgumentError, 'invalid value for "business_phone", the character length must be smaller than or equal to 20.'
      end

      if !business_phone.nil? && business_phone.to_s.length < 7
        fail ArgumentError, 'invalid value for "business_phone", the character length must be great than or equal to 7.'
      end

      @business_phone = business_phone
    end

    # Custom attribute writer method with validation
    # @param [Object] job_title Value to be assigned
    def job_title=(job_title)
      if !job_title.nil? && job_title.to_s.length > 45
        fail ArgumentError, 'invalid value for "job_title", the character length must be smaller than or equal to 45.'
      end

      @job_title = job_title
    end

    # Custom attribute writer method with validation
    # @param [Object] department Value to be assigned
    def department=(department)
      if !department.nil? && department.to_s.length > 45
        fail ArgumentError, 'invalid value for "department", the character length must be smaller than or equal to 45.'
      end

      @department = department
    end

    # Custom attribute writer method with validation
    # @param [Object] avatar Value to be assigned
    def avatar=(avatar)
      if !avatar.nil? && avatar.to_s.length > 255
        fail ArgumentError, 'invalid value for "avatar", the character length must be smaller than or equal to 255.'
      end

      @avatar = avatar
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] language Object to be assigned
    def language=(language)
      validator = EnumAttributeValidator.new('Object', ["fr", "en", "ja", "de", "es"])
      unless validator.valid?(language)
        fail ArgumentError, "invalid value for \"language\", must be one of #{validator.allowable_values}."
      end
      @language = language
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] is_primary Object to be assigned
    def is_primary=(is_primary)
      validator = EnumAttributeValidator.new('Object', ["1", "0"])
      unless validator.valid?(is_primary)
        fail ArgumentError, "invalid value for \"is_primary\", must be one of #{validator.allowable_values}."
      end
      @is_primary = is_primary
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Object', ["active", "disabled", "terminated"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] vm_greeting_type Object to be assigned
    def vm_greeting_type=(vm_greeting_type)
      validator = EnumAttributeValidator.new('Object', ["default", "mp3", "number"])
      unless validator.valid?(vm_greeting_type)
        fail ArgumentError, "invalid value for \"vm_greeting_type\", must be one of #{validator.allowable_values}."
      end
      @vm_greeting_type = vm_greeting_type
    end

    # Custom attribute writer method with validation
    # @param [Object] vm_playback_number Value to be assigned
    def vm_playback_number=(vm_playback_number)
      if !vm_playback_number.nil? && vm_playback_number.to_s.length > 20
        fail ArgumentError, 'invalid value for "vm_playback_number", the character length must be smaller than or equal to 20.'
      end

      @vm_playback_number = vm_playback_number
    end

    # Custom attribute writer method with validation
    # @param [Object] caller_id_number Value to be assigned
    def caller_id_number=(caller_id_number)
      if !caller_id_number.nil? && caller_id_number.to_s.length > 20
        fail ArgumentError, 'invalid value for "caller_id_number", the character length must be smaller than or equal to 20.'
      end

      @caller_id_number = caller_id_number
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] admin_permission Object to be assigned
    def admin_permission=(admin_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(admin_permission)
        fail ArgumentError, "invalid value for \"admin_permission\", must be one of #{validator.allowable_values}."
      end
      @admin_permission = admin_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_permission Object to be assigned
    def billing_permission=(billing_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(billing_permission)
        fail ArgumentError, "invalid value for \"billing_permission\", must be one of #{validator.allowable_values}."
      end
      @billing_permission = billing_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_permission Object to be assigned
    def phone_permission=(phone_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(phone_permission)
        fail ArgumentError, "invalid value for \"phone_permission\", must be one of #{validator.allowable_values}."
      end
      @phone_permission = phone_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] agile_permission Object to be assigned
    def agile_permission=(agile_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(agile_permission)
        fail ArgumentError, "invalid value for \"agile_permission\", must be one of #{validator.allowable_values}."
      end
      @agile_permission = agile_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] job_server_permission Object to be assigned
    def job_server_permission=(job_server_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(job_server_permission)
        fail ArgumentError, "invalid value for \"job_server_permission\", must be one of #{validator.allowable_values}."
      end
      @job_server_permission = job_server_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] media_server_permission Object to be assigned
    def media_server_permission=(media_server_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(media_server_permission)
        fail ArgumentError, "invalid value for \"media_server_permission\", must be one of #{validator.allowable_values}."
      end
      @media_server_permission = media_server_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mail_server_permission Object to be assigned
    def mail_server_permission=(mail_server_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(mail_server_permission)
        fail ArgumentError, "invalid value for \"mail_server_permission\", must be one of #{validator.allowable_values}."
      end
      @mail_server_permission = mail_server_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] super_admin_permission Object to be assigned
    def super_admin_permission=(super_admin_permission)
      validator = EnumAttributeValidator.new('Object', ["r", "rw", "null"])
      unless validator.valid?(super_admin_permission)
        fail ArgumentError, "invalid value for \"super_admin_permission\", must be one of #{validator.allowable_values}."
      end
      @super_admin_permission = super_admin_permission
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] vm_transcription Object to be assigned
    def vm_transcription=(vm_transcription)
      validator = EnumAttributeValidator.new('Object', ["1", "0"])
      unless validator.valid?(vm_transcription)
        fail ArgumentError, "invalid value for \"vm_transcription\", must be one of #{validator.allowable_values}."
      end
      @vm_transcription = vm_transcription
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email == o.email &&
          password == o.password &&
          sip_password == o.sip_password &&
          turn_password == o.turn_password &&
          first == o.first &&
          last == o.last &&
          mobile_phone == o.mobile_phone &&
          business_phone == o.business_phone &&
          extension == o.extension &&
          custom_caller_id == o.custom_caller_id &&
          job_title == o.job_title &&
          department == o.department &&
          office == o.office &&
          avatar == o.avatar &&
          language == o.language &&
          is_primary == o.is_primary &&
          status == o.status &&
          vm_greeting_type == o.vm_greeting_type &&
          vm_timeout == o.vm_timeout &&
          vm_file == o.vm_file &&
          vm_playback_number == o.vm_playback_number &&
          pin == o.pin &&
          number == o.number &&
          region == o.region &&
          caller_id_number == o.caller_id_number &&
          admin_permission == o.admin_permission &&
          billing_permission == o.billing_permission &&
          phone_permission == o.phone_permission &&
          agile_permission == o.agile_permission &&
          job_server_permission == o.job_server_permission &&
          media_server_permission == o.media_server_permission &&
          mail_server_permission == o.mail_server_permission &&
          super_admin_permission == o.super_admin_permission &&
          timezone == o.timezone &&
          vm_transcription == o.vm_transcription &&
          communication == o.communication
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email, password, sip_password, turn_password, first, last, mobile_phone, business_phone, extension, custom_caller_id, job_title, department, office, avatar, language, is_primary, status, vm_greeting_type, vm_timeout, vm_file, vm_playback_number, pin, number, region, caller_id_number, admin_permission, billing_permission, phone_permission, agile_permission, job_server_permission, media_server_permission, mail_server_permission, super_admin_permission, timezone, vm_transcription, communication].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CircuitIDAPIClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
